### ISSUE TITLE
META: Добавить конфигурации авто-форматирования файлов и проверки pre-commit

### ISSUE THREAD

**Issue by iigaz** [onied/main#8]
На данный момент каждый пишет в своем стиле, и в своем редакторе. Нужно унифицировать стиль. Для этого можно использовать pre-commit, но его нужно настроить. Этот issue больше как to-do, но можете добавить сюда пожелания по стилям или форматтерам, или правилам.

- [x] Не коммитить на main
- [x] Форматтер для C# (не определено, какой именно)
- [x] Форматтер для JS/JSX (не определено, какой именно)
- [x] Форматтер для HTML / CSS (не определено, какой именно)
